import { ProductData } from './types';

export const allProducts: ProductData[] = [
  {
    slug: 'custom-mugs',
    name: 'Custom Mugs',
    category: 'Drinkware',
    tagline: 'The daily ritual, branded with purpose',
    description: 'Premium ceramic and stainless steel mugs that transform everyday coffee moments into brand touchpoints. Designed for dishwasher-safe durability and vibrant full-color printing that stays true through thousands of washes.',
    accentColor: '#D97706',
    heroGradient: 'from-amber-50/60 via-ivory to-white',
    minQty: '50',
    leadTime: '12–15 days',
    priceRange: '₹180 – ₹350 per unit',
    pricePerUnit: 180,
    currency: 'INR',
    materials: [
      { name: 'Bone China', description: 'Thin-walled, translucent elegance with exceptional print clarity', color: '#F5E6D3' },
      { name: 'Stoneware', description: 'Dense, durable body with natural earthy texture', color: '#C4A882' },
      { name: 'Stainless Steel', description: 'Double-wall vacuum insulation for temperature retention', color: '#B8C4CE' },
      { name: 'Bamboo Fibre', description: 'Sustainable composite with warm organic feel', color: '#D4C5A9' },
    ],
    features: [
      { title: 'Dishwasher-Safe Print', description: 'Sublimation and screen printing methods that resist fading, scratching, and peeling through years of daily use and commercial washing cycles.' },
      { title: 'Full-Wrap Design', description: '360-degree print coverage with seamless artwork that flows around the entire surface of the mug for maximum visual impact.' },
      { title: 'Color-Matched Interiors', description: 'Interior glazing in brand colors for a premium two-tone effect that elevates perceived value.' },
      { title: 'Individual Gift Packaging', description: 'Optional Kraft or rigid boxes with foam inserts for safe shipping and unboxing moments.' },
    ],
    useCases: [
      { title: 'Employee Welcome Kits', description: 'A warm welcome in ceramic form. Every morning coffee becomes a subtle reminder of belonging.', solutionLink: '/solutions/employee-welcome-kits' },
      { title: 'Client Appreciation', description: 'Premium bone china with gold accents for VIP gifting that sits on desks, not in drawers.', solutionLink: '/solutions/corporate-gifting' },
      { title: 'Conference & Events', description: 'Branded travel mugs for attendees—useful during the event, indispensable after.', solutionLink: '/solutions/event-branding' },
    ],
    customizationOptions: [
      { name: 'Screen Printing', description: 'Vibrant, durable single to six-color designs. Best for bold logos and patterns.' },
      { name: 'Sublimation Print', description: 'Full-color photographic-quality prints with unlimited color complexity.' },
      { name: 'Embossed Logo', description: 'Subtle raised relief for a tactile premium feel that signals luxury.' },
      { name: 'Metallic Finish', description: 'Gold, silver, or rose gold rim and handle accents for executive gifts.' },
      { name: 'Interior Color Match', description: 'Glaze the interior in any Pantone shade for a striking two-tone effect.' },
      { name: 'Gift Box Insert', description: 'Custom-cut foam or moulded pulp packaging with branded sleeve.' },
    ],
  },
  {
    slug: 'branded-bottles',
    name: 'Branded Bottles',
    category: 'Drinkware',
    tagline: 'Hydration that carries your brand everywhere',
    description: 'Stainless steel, glass, and aluminium bottles built for performance and style. Every sip is a brand impression—at the gym, in meetings, on commutes.',
    accentColor: '#0D9488',
    heroGradient: 'from-teal-50/50 via-ivory to-white',
    minQty: '50',
    leadTime: '14–18 days',
    priceRange: '₹250 – ₹550 per unit',
    pricePerUnit: 250,
    currency: 'INR',
    materials: [
      { name: '304 Stainless Steel', description: 'Food-grade, corrosion-resistant with vacuum insulation', color: '#C5C9D0' },
      { name: 'Borosilicate Glass', description: 'Thermal-shock resistant with pure taste neutrality', color: '#E8EDF2' },
      { name: 'Recycled Aluminium', description: 'Lightweight, infinitely recyclable with modern finish', color: '#B8C4CE' },
      { name: 'Tritan BPA-Free', description: 'Crystal clarity with impact resistance and safety', color: '#D0E8F0' },
    ],
    features: [
      { title: 'Vacuum Insulation', description: 'Double-wall construction keeps beverages hot for 12 hours or cold for 24 hours.' },
      { title: 'Leak-Proof Lid', description: 'Silicone-sealed caps with one-hand operation for active lifestyles.' },
      { title: 'Laser Engraving', description: 'Permanent, tactile branding that never fades or peels.' },
      { title: 'Carabiner Carry Loop', description: 'Integrated clip for bags, belts, and gear attachment.' },
    ],
    useCases: [
      { title: 'Wellness Programs', description: 'Encourage hydration habits while keeping your brand in hand all day.', solutionLink: '/solutions/employee-welcome-kits' },
      { title: 'Sports & Fitness Events', description: 'Performance bottles for marathons, gyms, and outdoor activations.', solutionLink: '/solutions/event-branding' },
      { title: 'Sustainability Campaigns', description: 'Replace single-use plastic with reusable branded alternatives.', solutionLink: '/solutions/startup-branding' },
    ],
    customizationOptions: [
      { name: 'Laser Engraving', description: 'Precise permanent marking with metallic depth on steel or aluminium.' },
      { name: 'Full-Color Wrap', description: 'Photographic-quality 360-degree print with protective overcoat.' },
      { name: 'Soft-Touch Coating', description: 'Matte rubberized finish in custom colors with anti-slip grip.' },
      { name: 'Silicone Band Print', description: 'Contrasting grip band with debossed or printed logo.' },
      { name: 'Temperature Display Lid', description: 'Digital LED temperature readout for premium tech appeal.' },
      { name: 'Neoprene Sleeve', description: 'Custom-printed protective sleeve with shoulder strap option.' },
    ],
  },
  {
    slug: 'premium-notebooks',
    name: 'Premium Notebooks',
    category: 'Stationery',
    tagline: 'Ideas deserve a worthy vessel',
    description: 'Hardcover and softcover notebooks with lay-flat binding, premium paper stocks, and debossed or foil-stamped branding. The thinking companion your team and clients reach for daily.',
    accentColor: '#7C3AED',
    heroGradient: 'from-violet-50/50 via-ivory to-white',
    minQty: '50',
    leadTime: '10–14 days',
    priceRange: '₹120 – ₹280 per unit',
    pricePerUnit: 120,
    currency: 'INR',
    materials: [
      { name: 'Italian PU Leather', description: 'Supple, durable cover with rich color saturation', color: '#8B7355' },
      { name: 'Linen Hardcover', description: 'Textured natural fabric with tactile sophistication', color: '#D4CFC4' },
      { name: 'Recycled Kraft', description: 'Eco-conscious uncoated stock with raw authenticity', color: '#C4A882' },
      { name: 'FSC-Certified Paper', description: '80–120gsm cream or white with smooth writing', color: '#F5F0E8' },
    ],
    features: [
      { title: 'Lay-Flat Binding', description: 'Opens completely flat at any page for effortless two-page spreads.' },
      { title: 'Ribbon Bookmark', description: 'Color-matched satin ribbon for quick section access.' },
      { title: 'Elastic Closure', description: 'Keeps pages secure during travel and daily commutes.' },
      { title: 'Pen Loop', description: 'Integrated holder so a pen is always at hand.' },
    ],
    useCases: [
      { title: 'Onboarding Kits', description: 'A blank canvas for new ideas, given to every new hire.', solutionLink: '/solutions/employee-welcome-kits' },
      { title: 'Executive Gifting', description: 'Debossed leather with gold foil for C-suite appreciation.', solutionLink: '/solutions/corporate-gifting' },
      { title: 'Workshop & Training', description: 'Branded notebooks for participants to capture learnings.', solutionLink: '/solutions/event-branding' },
    ],
    customizationOptions: [
      { name: 'Debossed Logo', description: 'Pressed-in relief with subtle shadow for understated elegance.' },
      { name: 'Foil Stamping', description: 'Metallic gold, silver, copper, or holographic accents.' },
      { name: 'Custom Endpapers', description: 'Full-color printed inside covers with brand story or patterns.' },
      { name: 'Page Layout Options', description: 'Ruled, dotted, grid, blank, or mixed sections per notebook.' },
      { name: 'Printed Page Headers', description: 'Branded headers on every page with contact info or quotes.' },
      { name: 'Sleeve & Belly Band', description: 'Printed Kraft wrap with product details or messaging.' },
    ],
  },
  {
    slug: 'id-cards',
    name: 'ID Cards & Badges',
    category: 'Identity',
    tagline: 'Identity you can hold in your hand',
    description: 'Professional PVC, metal, and bamboo ID cards and badges with full-color printing, chip encoding, and lanyard customization. Security and brand presence in one card.',
    accentColor: '#2563EB',
    heroGradient: 'from-blue-50/50 via-ivory to-white',
    minQty: '25',
    leadTime: '7–10 days',
    priceRange: '₹45 – ₹120 per unit',
    pricePerUnit: 45,
    currency: 'INR',
    materials: [
      { name: 'PVC Composite', description: 'Durable, flexible with vibrant edge-to-edge print', color: '#E8EDF2' },
      { name: 'Brushed Metal', description: 'Aluminium with industrial-grade laser engraving', color: '#B8C4CE' },
      { name: 'Bamboo Composite', description: 'Sustainable wood-fibre with warm natural grain', color: '#D4C5A9' },
      { name: 'Polycarbonate', description: 'High-impact, tamper-resistant for secure access', color: '#D0D8E0' },
    ],
    features: [
      { title: 'RFID/NFC Encoding', description: 'Integrated chip encoding for access control and cashless payments.' },
      { title: 'Holographic Overlay', description: 'Security laminate with custom hologram to prevent counterfeiting.' },
      { title: 'Dual-Sided Print', description: 'Full-color front with monochrome or color reverse for maximum data.' },
      { title: 'Slot Punch & Clip', description: 'Reinforced slot with metal or plastic clip attachment.' },
    ],
    useCases: [
      { title: 'Corporate Security', description: 'Access-controlled cards with photo ID and department color coding.', solutionLink: '/solutions/employee-welcome-kits' },
      { title: 'Event Accreditation', description: 'NFC-enabled badges for entry, networking, and lead capture.', solutionLink: '/solutions/event-branding' },
      { title: 'Membership Programs', description: 'Metal VIP cards that members proudly carry in their wallets.', solutionLink: '/solutions/custom-merchandise' },
    ],
    customizationOptions: [
      { name: 'Dye-Sublimation Print', description: 'Photo-quality full-color with durable overlaminate protection.' },
      { name: 'Laser Engraving', description: 'Permanent, precise marking on metal and bamboo cards.' },
      { name: 'Chip Encoding', description: 'MIFARE, DESFire, or NFC NTAG programming with data.' },
      { name: 'Variable Data', description: 'Unique names, IDs, barcodes, and QR codes per card.' },
      { name: 'Lanyard Printing', description: 'Full-color lanyards with safety breakaway clips.' },
      { name: 'Retractable Reel', description: 'Branded chrome or plastic reel with belt clip.' },
    ],
  },
  {
    slug: 'custom-packaging',
    name: 'Custom Packaging',
    category: 'Packaging',
    tagline: 'The unboxing is part of the product',
    description: 'Rigid boxes, mailers, tubes, and pouches that transform product delivery into a brand experience. Sustainable materials, magnetic closures, and full CMYK printing.',
    accentColor: '#8B5CF6',
    heroGradient: 'from-purple-50/50 via-ivory to-white',
    minQty: '200',
    leadTime: '18–25 days',
    priceRange: '₹35 – ₹150 per unit',
    pricePerUnit: 35,
    currency: 'INR',
    materials: [
      { name: 'Rigid Paperboard', description: '2mm chipboard wrapped in printed paper for luxury feel', color: '#E8DED0' },
      { name: 'Kraft Corrugated', description: 'Recycled, biodegradable with natural texture', color: '#C4A882' },
      { name: 'FSC-Certified Paper', description: 'Sustainably sourced with chain-of-custody certification', color: '#D4CFC4' },
      { name: 'Cotton Paper', description: 'Handmade texture with embedded fibre for artisanal luxury', color: '#E8E0D4' },
    ],
    features: [
      { title: 'Magnetic Closure', description: 'Invisible magnets for a satisfying snap-close experience.' },
      { title: 'Spot UV & Foil', description: 'Selective gloss and metallic accents for tactile contrast.' },
      { title: 'Custom Die-Cut Inserts', description: 'Foam or moulded pulp that cradles products precisely.' },
      { title: 'Sustainable Certification', description: 'FSC, recyclable, and compostable options with printed logos.' },
    ],
    useCases: [
      { title: 'Product Launches', description: 'Launch kits that create anticipation before the product is revealed.', solutionLink: '/solutions/packaging-solutions' },
      { title: 'E-Commerce Shipping', description: 'Branded unboxing that turns delivery into a shareable moment.', solutionLink: '/solutions/packaging-solutions' },
      { title: 'Subscription Boxes', description: 'Monthly themed packaging that builds long-term brand love.', solutionLink: '/solutions/custom-merchandise' },
    ],
    customizationOptions: [
      { name: 'Embossed Logo', description: 'Raised relief on lid or front panel for premium feel.' },
      { name: 'Foil Stamping', description: 'Metallic accents in gold, silver, copper, or holographic.' },
      { name: 'Spot UV Varnish', description: 'Gloss highlights over matte laminate for visual depth.' },
      { name: 'Custom Insert Design', description: 'Die-cut foam, pulp, or card to fit your exact product.' },
      { name: 'Ribbon Pull', description: 'Satin or grosgrain ribbon for elegant product extraction.' },
      { name: 'Tissue & Stickers', description: 'Branded tissue paper and seal stickers for finishing touch.' },
    ],
  },
  {
    slug: 'corporate-gifts',
    name: 'Corporate Gifts',
    category: 'Gifting',
    tagline: 'Appreciation, delivered with intention',
    description: 'Curated gift sets and individual items for client appreciation, employee recognition, and milestone celebrations. Every piece selected to reflect your brand values.',
    accentColor: '#DC2626',
    heroGradient: 'from-red-50/50 via-ivory to-white',
    minQty: '25',
    leadTime: '10–18 days',
    priceRange: '₹500 – ₹2,500 per unit',
    pricePerUnit: 500,
    currency: 'INR',
    materials: [
      { name: 'Italian Leather', description: 'Full-grain with natural patina aging', color: '#8B7355' },
      { name: 'Walnut Wood', description: 'American black walnut with rich grain', color: '#6B4F3A' },
      { name: 'Brass & Copper', description: 'Solid metal with hand-polished finish', color: '#C4A35A' },
      { name: 'Merino Wool', description: 'Fine, soft natural fibre with temperature regulation', color: '#D4CFC4' },
    ],
    features: [
      { title: 'Curated Selection', description: 'Pre-designed gift sets or fully custom combinations of 3–12 items.' },
      { title: 'Personalized Messaging', description: 'Individual names, messages, or dates on each item.' },
      { title: 'Premium Gift Boxes', description: 'Rigid presentation boxes with magnetic closure and ribbon.' },
      { title: 'Direct Shipping', description: 'Individual address shipping with branded packaging per recipient.' },
    ],
    useCases: [
      { title: 'Client Appreciation', description: 'Thoughtful sets that strengthen relationships beyond transactions.', solutionLink: '/solutions/corporate-gifting' },
      { title: 'Employee Recognition', description: 'Milestone and performance gifts that feel genuinely personal.', solutionLink: '/solutions/employee-welcome-kits' },
      { title: 'Festival Gifting', description: 'Diwali, Christmas, Eid, and New Year hampers with cultural sensitivity.', solutionLink: '/solutions/corporate-gifting' },
    ],
    customizationOptions: [
      { name: 'Name Engraving', description: 'Individual personalization on metal, wood, or leather items.' },
      { name: 'Custom Message Card', description: 'Handwritten-style printed cards with your message.' },
      { name: 'Gift Box Design', description: 'Fully printed rigid box with your brand colors and patterns.' },
      { name: 'Curated Combinations', description: 'Mix and match from 100+ items to build your perfect set.' },
      { name: 'Ribbon & Seal', description: 'Custom-printed ribbon and wax seal stickers.' },
      { name: 'Direct Dispatch', description: 'Ship to individual addresses with tracking per recipient.' },
    ],
  },
  {
    slug: 'employee-kits',
    name: 'Employee Kits',
    category: 'Kits',
    tagline: 'Onboarding that starts before day one',
    description: 'Complete welcome and work-from-home kits with branded essentials that make every employee feel valued from the moment they join. Purpose-built for distributed teams.',
    accentColor: '#059669',
    heroGradient: 'from-emerald-50/50 via-ivory to-white',
    minQty: '25',
    leadTime: '14–21 days',
    priceRange: '₹800 – ₹3,500 per unit',
    pricePerUnit: 800,
    currency: 'INR',
    materials: [
      { name: 'Recycled PET Fabric', description: 'From plastic bottles to premium textile', color: '#B8C4CE' },
      { name: 'Organic Cotton', description: 'GOTS-certified with natural softness', color: '#D4CFC4' },
      { name: 'Cork', description: 'Renewable, lightweight with unique grain', color: '#C4A882' },
      { name: 'Recycled Paper', description: 'Post-consumer waste with texture and character', color: '#E8E0D4' },
    ],
    features: [
      { title: 'Complete Experience', description: 'Everything needed for day one: notebook, pen, bottle, mug, and bag.' },
      { title: 'Remote-Ready', description: 'Compact, lightweight packaging designed for courier delivery.' },
      { title: 'Role-Based Customization', description: 'Different kit compositions for engineering, sales, design, and leadership.' },
      { title: 'Welcome Card', description: 'Personalized message from the CEO or direct manager.' },
    ],
    useCases: [
      { title: 'New Hire Onboarding', description: 'A tangible welcome that makes remote onboarding feel human.', solutionLink: '/solutions/employee-welcome-kits' },
      { title: 'Work-From-Home Setup', description: 'Branded essentials that transform home desks into productive spaces.', solutionLink: '/solutions/employee-welcome-kits' },
      { title: 'Team Retreats', description: 'Pre-event kits that build excitement before the gathering.', solutionLink: '/solutions/event-branding' },
    ],
    customizationOptions: [
      { name: 'Kit Configuration', description: 'Choose from 5, 7, or 10-item kits with mix-and-match flexibility.' },
      { name: 'Role-Based Items', description: 'Tech accessories for engineers, notebooks for creatives, etc.' },
      { name: 'Welcome Card Design', description: 'Custom-printed card with employee name and team details.' },
      { name: 'Tote/Bag Printing', description: 'Canvas or recycled PET tote with full-color print.' },
      { name: 'T-Shirt/Apparel', description: 'Sized organic cotton tee or polo with brand design.' },
      { name: 'Desk Accessories', description: 'Mouse pad, pen stand, cable organizer with brand presence.' },
    ],
  },
];

export function getProductBySlug(slug: string): ProductData | undefined {
  return allProducts.find((p) => p.slug === slug);
}

export function getRelatedProducts(currentSlug: string, limit = 3): ProductData[] {
  const current = getProductBySlug(currentSlug);
  if (!current) return [];

  return allProducts
    .filter((p) => p.slug !== currentSlug)
    .sort((a, b) => {
      const aSame = a.category === current.category ? 2 : a.category === current.category ? 1 : 0;
      const bSame = b.category === current.category ? 2 : b.category === current.category ? 1 : 0;
      return bSame - aSame;
    })
    .slice(0, limit);
}
